spring:
  application:
    name: ai-gw

  ai:
    google:
      genai:
        api-key: 
        project-id: 
        chat:
          options:
            model: 

server:
  port: 5000
  servlet:
    context-path: /api/spring/v1

user:
  dir: /Users/cheloniaMD/workspace/whois/backend/spring/
