spring:
  application:
    name: ai-gw

  ai:
    google:
      genai:
        api-key: 
        project-id: projects/252168514844
        chat:
          options:
            model: models/gemini-2.5-pro

server:
  port: 5000
  servlet:
    context-path: /api/spring/v1

user:
  dir: /Users/cheloniaMD/workspace/whois/backend/spring/
