apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whois-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: whois.valuechain.lol
    http:
      paths:
      # Fiber API - rewrite 있음
      - path: /api/go
        pathType: Prefix
        backend:
          service:
            name: fiber-service
            port:
              number: 80
      
      # Spring API - rewrite 있음
      - path: /api/spring
        pathType: Prefix
        backend:
          service:
            name: spring-service
            port:
              number: 80
      
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
